### ISSUE TITLE
[usb1208FS] usb1.USBErrorBusy: LIBUSB_ERROR_BUSY [-6]

### ISSUE THREAD

**Issue by WillForan** [wjasper/Linux_Drivers#45]
https://github.com/commaai/panda/issues/154 suggests `self.udev.setAutoDetachKernelDriver(True)`. I tried adding that before `claimInterface` but that didn't help. 

```
python test-usb1208FS.py 
Traceback (most recent call last):
  File "/home/abel/luna_habit/usb1208fs-linux-drivers/USB/python/test-usb1208FS.py", line 239, in <module>
    main()
  File "/home/abel/luna_habit/usb1208fs-linux-drivers/USB/python/test-usb1208FS.py", line 34, in main
    usb1208FS = usb_1208FS()
  File "/home/abel/luna_habit/usb1208fs-linux-drivers/USB/python/usb_1208FS.py", line 117, in __init__
    self.udev.claimInterface(i)
  File "/home/abel/anaconda3/lib/python3.9/site-packages/usb1/__init__.py", line 1146, in claimInterface
    mayRaiseUSBError(
  File "/home/abel/anaconda3/lib/python3.9/site-packages/usb1/__init__.py", line 127, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/home/abel/anaconda3/lib/python3.9/site-packages/usb1/__init__.py", line 119, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorBusy: LIBUSB_ERROR_BUSY [-6]
```

```
lsusb
Bus 004 Device 010: ID 0bda:8153 Realtek Semiconductor Corp. 
Bus 004 Device 009: ID 2537:1081  
Bus 004 Device 008: ID 2109:0813 VIA Labs, Inc. 
Bus 004 Device 007: ID 2109:0813 VIA Labs, Inc. 
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 004: ID 05ac:100e Apple, Inc. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 017: ID 0c76:161f JMTek, LLC. 
Bus 001 Device 012: ID 2109:2813 VIA Labs, Inc. 
Bus 001 Device 011: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC
Bus 001 Device 018: ID 09db:0082 Measurement Computing Corp. USB-1208FS
Bus 001 Device 010: ID 2109:2813 VIA Labs, Inc. 
Bus 001 Device 005: ID 0489:e0a2 Foxconn / Hon Hai 
Bus 001 Device 003: ID 0c45:6723 Microdia 
Bus 001 Device 004: ID 05ac:1460 Apple, Inc. 
Bus 001 Device 002: ID 05ac:100f Apple, Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

```
uname -a
Linux abel-XPS-13-9380 5.4.0-126-generic #142~18.04.1-Ubuntu SMP Thu Sep 1 16:25:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

python --version
Python 3.9.12
```

I'm not sure if COMEDI would be an issue, but I don't see it in the module list.
```
lsmod | grep -o  'cb|[0-9]_pci' # empty
```

**Comment by WillForan** [comment]
ah. I unplugged the usb hub and plugged it back in. Problem solved
